on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm clean-install
      - run: npm run build
      - run: npm exec --yes vsce@latest -- publish --pat ${{ secrets.AZURE_DEVOPS_PAT }}
