on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install -g vsce
      - run: npm install
      - run: npm run build
      - run: vsce publish --pat ${{ secrets.AZURE_DEVOPS_PAT }}
